let jobInformation = {};
jobInformation.jobList = [
    {id: 0, name: "戦士", powerGrowth: 16, manaGrowth: 4, religionGrowth: 8, vitalityGrowth: 16, agilityGrowth: 4, dexterityGrowth: 4, charmGrowth: 6, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [1],masterArts:[2]},
    { id: 1, name: "魔法使い", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3],masterArts:[4]},
    { id: 2, name: "僧侶", powerGrowth: 4, manaGrowth: 16, religionGrowth: 16, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 10, karmaGrowth: 10 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [5, 6],masterArts:[7]},
    { id: 3, name: "盗賊", powerGrowth: 8, manaGrowth: 6, religionGrowth: 4, vitalityGrowth: 10, agilityGrowth: 16, dexterityGrowth: 16, charmGrowth: 4, karmaGrowth: 4, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [8, 9], masterArts: [10] },
    { id: 4, name: "", powerGrowth: 16, manaGrowth: 4, religionGrowth: 8, vitalityGrowth: 16, agilityGrowth: 4, dexterityGrowth: 4, charmGrowth: 6, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [1],masterArts:[2]},
    { id: 5, name: "魔法使い", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3],masterArts:[4]},
    { id: 6, name: "僧侶", powerGrowth: 4, manaGrowth: 16, religionGrowth: 16, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 10, karmaGrowth: 10 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [5, 6],masterArts:[7]},
    { id: 7, name: "盗賊", powerGrowth: 8, manaGrowth: 6, religionGrowth: 4, vitalityGrowth: 10, agilityGrowth: 16, dexterityGrowth: 16, charmGrowth: 4, karmaGrowth: 4, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [8, 9], masterArts: [10] },
    { id: 999, name: "管理人", powerGrowth: 127, manaGrowth: 127, religionGrowth: 127, vitalityGrowth: 127, agilityGrowth: 127, dexterityGrowth: 127, charmGrowth: 127, karmaGrowth: 127, powerRequired: 100000000, manaRequired: 100000000, religionRequired: 100000000, vitalityRequired: 100000000, agilityRequired: 100000000, dexterityRequired: 100000000, charmRequired: 100000000, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [999, 1000], masterArts: [10000] }
];

module.exports = jobInformation;