let jobInformation = {};
jobInformation.jobList = [
    {id: 0, name: "戦士", powerGrowth: 16, manaGrowth: 4, religionGrowth: 8, vitalityGrowth: 16, agilityGrowth: 4, dexterityGrowth: 4, charmGrowth: 6, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [1],masterArts:[2],jobsRequired: []},
    { id: 1, name: "魔法使い", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: []},
    { id: 2, name: "僧侶", powerGrowth: 4, manaGrowth: 16, religionGrowth: 16, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 10, karmaGrowth: 10 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [5, 6],masterArts:[7], jobsRequired: []},
    { id: 3, name: "盗賊", powerGrowth: 8, manaGrowth: 6, religionGrowth: 4, vitalityGrowth: 10, agilityGrowth: 16, dexterityGrowth: 16, charmGrowth: 4, karmaGrowth: 4, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [8, 9], masterArts: [10], jobsRequired:[]},
    { id: 4, name: "地術師", powerGrowth: 16, manaGrowth: 4, religionGrowth: 8, vitalityGrowth: 16, agilityGrowth: 4, dexterityGrowth: 4, charmGrowth: 6, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [1],masterArts:[2],jobsRequired:[]},
    { id: 5, name: "呪法師", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3],masterArts:[4],jobsRequired: [1]},
    { id: 6, name: "詩人", powerGrowth: 4, manaGrowth: 16, religionGrowth: 16, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 10, karmaGrowth: 10 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [5, 6],masterArts:[7],jobsRequired: []},
    { id: 7, name: "ほら吹き", powerGrowth: 8, manaGrowth: 8, religionGrowth: 8, vitalityGrowth: 8, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [8, 9], masterArts: [10],jobsRequired: [1] },
    { id: 8, name: "召喚士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [1] },
    { id: 9, name: "竜騎士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [0] },
    { id: 10, name: "僧正", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [1, 2] },
    { id: 11, name: "騎士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [0, 2] },
    { id: 12, name: "侍", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [0, 1] },
    { id: 13, name: "僧兵", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [2] },
    { id: 14, name: "乱波", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [3, 6] },
    { id: 15, name: "暗黒騎士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [1, 11] },
    { id: 16, name: "魔法戦士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [5, 6] },
    { id: 17, name: "ゲリラ兵", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [3, 4] },
    { id: 18, name: "幻獣使い", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [6, 7] },
    { id: 19, name: "帝", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [15, 16] },
    { id: 20, name: "パラディン", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [7,10, 15] },
    { id: 21, name: "卜占士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [6,8] },
    { id: 22, name: "管理人", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [18,19,20] },
    
    { id: 23, name: "オニオンソーディアン", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [] },
    { id: 24, name: "ヒットパーソン", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [] },
    { id: 25, name: "まものつかい", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [22, 24] },
    { id: 26, name: "賢者", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [22, 24] },
    { id: 27, name: "武聖", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [22, 24] },
    { id: 28, name: "アルカニスト", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [25,26,27] },
    { id: 29, name: "勇者", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [28] },
    { id: 30, name: "グランドマスター", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29] },

    //追加したい職業があったらグランドマスターに続けて記述
    { id: 999, name: "管理人", powerGrowth: 127, manaGrowth: 127, religionGrowth: 127, vitalityGrowth: 127, agilityGrowth: 127, dexterityGrowth: 127, charmGrowth: 127, karmaGrowth: 127, powerRequired: 100000000, manaRequired: 100000000, religionRequired: 100000000, vitalityRequired: 100000000, agilityRequired: 100000000, dexterityRequired: 100000000, charmRequired: 100000000, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [999, 1000], masterArts: [10000] }
];

module.exports = jobInformation;

//id22までが通常ジョブ，23以降が隠しジョブ