let jobInformation = {};
//職業情報 
//各種能力の成長率，要求される各種能力値，x屋に並ぶx(x \in {"武器","防具","装飾品"})，転職することで使えるようになるスキル，マスターすることで使えるようになるスキル，要求される職歴(これらをマスターしていないと転職できない)を記述．
jobInformation.jobList = [
    { id: 0, name: "戦士", powerGrowth: 16, manaGrowth: 4, religionGrowth: 8, vitalityGrowth: 16, agilityGrowth: 4, dexterityGrowth: 4, charmGrowth: 6, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [1],masterArts:[2],jobsRequired: []},
    { id: 1, name: "魔法使い", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: []},
    { id: 2, name: "僧侶", powerGrowth: 4, manaGrowth: 16, religionGrowth: 16, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 10, karmaGrowth: 10 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [5, 6],masterArts:[7], jobsRequired: []},
    { id: 3, name: "盗賊", powerGrowth: 8, manaGrowth: 6, religionGrowth: 4, vitalityGrowth: 10, agilityGrowth: 16, dexterityGrowth: 16, charmGrowth: 4, karmaGrowth: 4, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [8, 9], masterArts: [10], jobsRequired:[]},
    { id: 4, name: "地術師", powerGrowth: 16, manaGrowth: 4, religionGrowth: 8, vitalityGrowth: 16, agilityGrowth: 4, dexterityGrowth: 4, charmGrowth: 6, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [11,12],masterArts:[],jobsRequired:[]},
    { id: 5, name: "嵐導士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [13,14],masterArts:[15],jobsRequired: [1]},
    { id: 6, name: "詩人", powerGrowth: 4, manaGrowth: 16, religionGrowth: 16, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 10, karmaGrowth: 10 ,powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [16,17],masterArts:[18],jobsRequired: []},
    { id: 7, name: "ほら吹き", powerGrowth: 8, manaGrowth: 8, religionGrowth: 8, vitalityGrowth: 8, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [], masterArts: [19],jobsRequired: [1] },
    { id: 8, name: "召喚士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [20,21], masterArts: [22], jobsRequired: [1] },
    { id: 9, name: "ドラグーン", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [23,24], masterArts: [25], jobsRequired: [0] },
    { id: 10, name: "僧正", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [1, 2] },
    { id: 11, name: "騎士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [0, 2] },
    { id: 12, name: "侍", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [0, 1] },
    { id: 13, name: "僧兵", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [2] },
    { id: 14, name: "乱波", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [3, 6] },
    { id: 15, name: "暗黒騎士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [1, 11] },
    { id: 16, name: "魔法戦士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [5, 6] },
    { id: 17, name: "ゲリラ兵", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [3, 4] },
    { id: 18, name: "幻獣使い", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [6, 7] },
    { id: 19, name: "帝", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [15, 16] },
    { id: 20, name: "パラディン", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [7, 10, 13, 15] },
    { id: 21, name: "卜占士", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [6,8] },
    { id: 22, name: "管理人", powerGrowth: 4, manaGrowth: 16, religionGrowth: 8, vitalityGrowth: 4, agilityGrowth: 8, dexterityGrowth: 8, charmGrowth: 8, karmaGrowth: 8, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [18,19,20] },
    
    { id: 23, name: "オニオンソーディアン", powerGrowth: 74, manaGrowth: 64, religionGrowth: 74, vitalityGrowth: 64, agilityGrowth: 74, dexterityGrowth: 64, charmGrowth: 74, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [] },
    { id: 24, name: "ヒットパーソン", powerGrowth: 34, manaGrowth: 64, religionGrowth: 64, vitalityGrowth: 124, agilityGrowth: 64, dexterityGrowth: 64, charmGrowth: 64, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [] },
    { id: 25, name: "まものつかい", powerGrowth: 64, manaGrowth: 64, religionGrowth: 64, vitalityGrowth: 64, agilityGrowth: 64, dexterityGrowth: 64, charmGrowth: 64, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [22, 24] },
    { id: 26, name: "賢者", powerGrowth: 64, manaGrowth: 64, religionGrowth: 64, vitalityGrowth: 64, agilityGrowth: 64, dexterityGrowth: 64, charmGrowth: 64, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [22, 24] },
    { id: 27, name: "武聖", powerGrowth: 64, manaGrowth: 64, religionGrowth: 64, vitalityGrowth: 64, agilityGrowth: 64, dexterityGrowth: 64, charmGrowth: 64, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [22, 24] },
    { id: 28, name: "アルカニスト", powerGrowth: 64, manaGrowth: 64, religionGrowth: 64, vitalityGrowth: 64, agilityGrowth: 64, dexterityGrowth: 64, charmGrowth: 64, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [25,26,27] },
    { id: 29, name: "勇者", powerGrowth: 64, manaGrowth: 64, religionGrowth: 64, vitalityGrowth: 64, agilityGrowth: 64, dexterityGrowth: 64, charmGrowth: 64, karmaGrowth: 64, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [28] },
    { id: 30, name: "グランドマスター", powerGrowth: 24, manaGrowth: 24, religionGrowth: 24, vitalityGrowth: 24, agilityGrowth: 24, dexterityGrowth: 24, charmGrowth: 24, karmaGrowth: 24, powerRequired: 0, manaRequired: 0, religionRequired: 0, vitalityRequired: 0, agilityRequired: 0, dexterityRequired: 0, charmRequired: 0, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29] },
    //追加したい職業があったらグランドマスターに続けて記述．id:31は例
    //{ id: 31, name: "星使い", powerGrowth: 48, manaGrowth: 48, religionGrowth: 48, vitalityGrowth: 48, agilityGrowth: 48, dexterityGrowth: 48, charmGrowth: 48, karmaGrowth: 48, powerRequired: 100000, manaRequired: 100000, religionRequired: 100000, vitalityRequired: 100000, agilityRequired: 100000, dexterityRequired: 100000, charmRequired: 100000, karmaRequired: 100000, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [3], masterArts: [4], jobsRequired: [30] },

    { id: 999, name: "管理人", powerGrowth: 999999, manaGrowth: 999999, religionGrowth: 999999, vitalityGrowth: 999999, agilityGrowth: 999999, dexterityGrowth: 999999, charmGrowth: 999999, karmaGrowth: 127, powerRequired: 100, manaRequired: 100, religionRequired: 100, vitalityRequired: 100, agilityRequired: 100, dexterityRequired: 100, charmRequired: 100, karmaRequired: 0, weapon: [1, 2, 3, 4], armor: [1, 2, 3, 4], accessory: [1, 2, 3, 4], basicArts: [999, 1000], masterArts: [10000], jobsRequired: [] }
];

let soldierAttack = (user) => user.weapon.attack + user.power;
let mageAttack = (user) => user.weapon.attak + user.mana;
let priestAttack = (user) => user.weapon.attack + user.religion;
let thiefAttack = (user) => user.weapon.attack + user.dexterity;
let soilmancerAttack = (user) => user.weapon.attack + user.mana;
let roilmageAttack = (user) => user.weapon.attack + user.mana;
let bardAttack = (user) => user.weapon.attack + user.mana + user.charm;
let blagueurAttack = (user) => user.power + user.mana + user.religion + user.dexterity + user.agility + user.vitality + user.charm + user.karma;
let summonerAttack = (user) => user.weapon.attack + user.mana + user.charm;
let dragoonAttack = (user) => user.weapon.attack + user.power + user.dexterity;
let bishopAttack = (user) => user.weapon.attack + user.mana + user.religion;
let knightAttack = (user) => user.weapon.attack + user.power + user.religion;
let samuraiAttack = (user) => user.weapon.attack + user.power + user.mana;
let monkAttack = (user) => user.power + user.vitality;
let ninjaAttack = (user) => user.weapon.attack + user.power + user.agility;
let darkKnightAttack = (user) => user.weapon.attack + user.power + user.mana;
let mageWarriorAttack = (user) => user.weapon.attack + user.power + user.mana;
let mercenaryArrack = (user) => user.weapon.attack + user.power + user.agility;
let tamerAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let emperorAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let paladinAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let augurAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let administratorAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let onionSwordianAttack = (user) => user.weapon.attack + user.power;
let assassinAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let monsterTamerAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let sageAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let masterValorAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let braveAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;
let grandMasterAttack = (user) => user.weapon.attack + user.power + user.mana + user.religion + user.vitality + user.agility + user.dexterity + user.charm + user.karma;






module.exports = jobInformation;

//id22までが通常ジョブ，23以降が隠しジョブ